In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
Netflixshow=pd.read_csv(r"C:\Users\pvino\Desktop\netflixData009.csv")

In [3]:
Netflixshow

,Show Id,Title,Description,Director,Genres,Cast,Production Country,Release Date,Rating,Duration,Imdb Score,Content Type,Date Added
0,cc1b6ed9-cf9e-4057-8303-34577fb54477,(Un)Well,This docuseries takes a deep dive into the luc...,NaN,Reality TV,NaN,United States,2020.0,TV-MA,1 Season,6.6/10,TV Show,NaN
1,e2ef4e91-fb25-42ab-b485-be8e3b23dedb,#Alive,"As a grisly virus rampages a city, a lone man ...",Cho Il,"Horror Movies, International Movies, Thrillers","Yoo Ah-in, Park Shin-hye",South Korea,2020.0,TV-MA,99 min,6.2/10,Movie,"September 8, 2020"
2,b01b73b7-81f6-47a7-86d8-acb63080d525,#AnneFrank - Parallel Stories,"Through her diary, Anne Frank's story is retol...","Sabina Fedeli, Anna Migotto","Documentaries, International Movies","Helen Mirren, Gengher Gatti",Italy,2019.0,TV-14,95 min,6.4/10,Movie,"July 1, 2020"
3,b6611af0-f53c-4a08-9ffa-9716dc57eb9c,#blackAF,Kenya Barris and his family navigate relations...,NaN,TV Comedies,"Kenya Barris, Rashida Jones, Iman Benson, Genn...",United States,2020.0,TV-MA,1 Season,6.6/10,TV Show,NaN
4,7f2d4170-bab8-4d75-adc2-197f7124c070,#cats_the_mewvie,This pawesome documentary explores how our fel...,Michael Margolis,"Documentaries, International Movies",NaN,Canada,2020.0,TV-14,90 min,5.1/10,Movie,"February 5, 2020"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5962,62b8b682-f191-4c10-aa04-32319329bd8d,الف مبروك,"On his wedding day, an arrogant, greedy accoun...",Ahmed Nader Galal,"Comedies, Dramas, International Movies","Ahmed Helmy, Laila Ezz El Arab, Mahmoud El Fis...",Egypt,2009.0,TV-14,115 min,7.4/10,Movie,"April 25, 2020"
5963,5bed77ab-5e31-4216-8b51-44c9a35442e6,دفعة القاهرة,A group of women leaves Kuwait to attend unive...,NaN,"International TV Shows, TV Dramas","Bashar al-Shatti, Fatima Al Safi, Maram Baloch...",NaN,2019.0,TV-14,1 Season,NaN,TV Show,NaN
5964,4661ec0c-8692-4661-bc76-a96412b311fd,海的儿子,"Two brothers start a new life in Singapore, wh...",NaN,"International TV Shows, TV Dramas","Li Nanxing, Christopher Lee, Jesseca Liu, Appl...",NaN,2016.0,TV-14,1 Season,NaN,TV Show,NaN
5965,145c93a7-1924-403c-a933-4ede8ad66f26,반드시 잡는다,After people in his town start turning up dead...,Hong-seon Kim,"Dramas, International Movies, Thrillers",Baek Yoon-sik,South Korea,2017.0,TV-MA,110 min,6.5/10,Movie,"February 28, 2018"
5966,d4613d34-cb71-4bd6-b570-fa857f02c44d,최강전사 미니특공대 : 영웅의 탄생,"Miniforce, a special task force of elite range...",Young Jun Lee,Children & Family Movies,"Um Sang-hyun, Yang Jeong-hwa, Jeon Tae-yeol, S...",NaN,2018.0,TV-Y7,68 min,4.7/10,Movie,"September 1, 2018"

In [6]:
Netflixshow.head()

,Show Id,Title,Description,Director,Genres,Cast,Production Country,Release Date,Rating,Duration,Imdb Score,Content Type,Date Added
0,cc1b6ed9-cf9e-4057-8303-34577fb54477,(Un)Well,This docuseries takes a deep dive into the luc...,NaN,Reality TV,NaN,United States,2020.0,TV-MA,1 Season,6.6/10,TV Show,NaN
1,e2ef4e91-fb25-42ab-b485-be8e3b23dedb,#Alive,"As a grisly virus rampages a city, a lone man ...",Cho Il,"Horror Movies, International Movies, Thrillers","Yoo Ah-in, Park Shin-hye",South Korea,2020.0,TV-MA,99 min,6.2/10,Movie,"September 8, 2020"
2,b01b73b7-81f6-47a7-86d8-acb63080d525,#AnneFrank - Parallel Stories,"Through her diary, Anne Frank's story is retol...","Sabina Fedeli, Anna Migotto","Documentaries, International Movies","Helen Mirren, Gengher Gatti",Italy,2019.0,TV-14,95 min,6.4/10,Movie,"July 1, 2020"
3,b6611af0-f53c-4a08-9ffa-9716dc57eb9c,#blackAF,Kenya Barris and his family navigate relations...,NaN,TV Comedies,"Kenya Barris, Rashida Jones, Iman Benson, Genn...",United States,2020.0,TV-MA,1 Season,6.6/10,TV Show,NaN
4,7f2d4170-bab8-4d75-adc2-197f7124c070,#cats_the_mewvie,This pawesome documentary explores how our fel...,Michael Margolis,"Documentaries, International Movies",NaN,Canada,2020.0,TV-14,90 min,5.1/10,Movie,"February 5, 2020"

In [7]:
Netflixshow.tail(10)

,Show Id,Title,Description,Director,Genres,Cast,Production Country,Release Date,Rating,Duration,Imdb Score,Content Type,Date Added
5957,309b0d7e-357b-45ce-b1cf-617b4c3593d5,Zoot Suit,"In this drama based on a 1940s trial, the memb...",Luis Valdez,"Cult Movies, Dramas, Music & Musicals","Daniel Valdez, Edward James Olmos, Charles Aid...",United States,1981.0,R,103 min,7.0/10,Movie,"April 15, 2021"
5958,a006d6c6-e213-4a8b-9f57-b941e822d0c5,Zozo,When Lebanon's Civil War deprives Zozo of his ...,Josef Fares,"Dramas, International Movies","Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...",2005.0,TV-MA,99 min,6.7/10,Movie,"October 19, 2020"
5959,29166831-eb84-4a0d-b2e0-e4c13fea7c6d,Zulu Man in Japan,"In this documentary, South African rapper Nast...",NaN,"Documentaries, International Movies, Music & M...",Nasty C,NaN,2019.0,TV-MA,44 min,NaN,Movie,"September 25, 2020"
5960,a86d832c-1082-4b10-82a3-766bb539e3aa,Zumbo's Just Desserts,Dessert wizard Adriano Zumbo looks for the nex...,NaN,"International TV Shows, Reality TV","Adriano Zumbo, Rachel Khoo",Australia,2019.0,TV-PG,1 Season,7.1/10,TV Show,"October 31, 2020"
5961,06aab7f2-9756-4680-98cf-209b7ca86a9b,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,This documentary delves into the mystique behi...,Sam Dunn,"Documentaries, Music & Musicals",NaN,"United Kingdom, Canada, United States",2019.0,TV-MA,90 min,7.4/10,Movie,"March 1, 2020"
5962,62b8b682-f191-4c10-aa04-32319329bd8d,الف مبروك,"On his wedding day, an arrogant, greedy accoun...",Ahmed Nader Galal,"Comedies, Dramas, International Movies","Ahmed Helmy, Laila Ezz El Arab, Mahmoud El Fis...",Egypt,2009.0,TV-14,115 min,7.4/10,Movie,"April 25, 2020"
5963,5bed77ab-5e31-4216-8b51-44c9a35442e6,دفعة القاهرة,A group of women leaves Kuwait to attend unive...,NaN,"International TV Shows, TV Dramas","Bashar al-Shatti, Fatima Al Safi, Maram Baloch...",NaN,2019.0,TV-14,1 Season,NaN,TV Show,NaN
5964,4661ec0c-8692-4661-bc76-a96412b311fd,海的儿子,"Two brothers start a new life in Singapore, wh...",NaN,"International TV Shows, TV Dramas","Li Nanxing, Christopher Lee, Jesseca Liu, Appl...",NaN,2016.0,TV-14,1 Season,NaN,TV Show,NaN
5965,145c93a7-1924-403c-a933-4ede8ad66f26,반드시 잡는다,After people in his town start turning up dead...,Hong-seon Kim,"Dramas, International Movies, Thrillers",Baek Yoon-sik,South Korea,2017.0,TV-MA,110 min,6.5/10,Movie,"February 28, 2018"
5966,d4613d34-cb71-4bd6-b570-fa857f02c44d,최강전사 미니특공대 : 영웅의 탄생,"Miniforce, a special task force of elite range...",Young Jun Lee,Children & Family Movies,"Um Sang-hyun, Yang Jeong-hwa, Jeon Tae-yeol, S...",NaN,2018.0,TV-Y7,68 min,4.7/10,Movie,"September 1, 2018"

In [8]:
Netflixshow.info()

<class 'pandas.DataFrame'>
RangeIndex: 5967 entries, 0 to 5966
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Show Id             5967 non-null   str
 1   Title               5967 non-null   str
 2   Description         5967 non-null   str
 3   Director            3903 non-null   str
 4   Genres              5967 non-null   str
 5   Cast                5437 non-null   str
 6   Production Country  5408 non-null   str
 7   Release Date        5964 non-null   float64
 8   Rating              5963 non-null   str
 9   Duration            5964 non-null   str
 10  Imdb Score          5359 non-null   str
 11  Content Type        5967 non-null   str
 12  Date Added          4632 non-null   str
dtypes: float64(1), str(12)
memory usage: 606.2 KB

In [9]:
Netflixshow.isnull().sum()

Show Id                  0
Title                    0
Description              0
Director              2064
Genres                   0
Cast                   530
Production Country     559
Release Date             3
Rating                   4
Duration                 3
Imdb Score             608
Content Type             0
Date Added            1335
dtype: int64

In [12]:
Netflixshow.columns

Index(['Show Id', 'Title', 'Description', 'Director', 'Genres', 'Cast',
       'Production Country', 'Release Date', 'Rating', 'Duration',
       'Imdb Score', 'Content Type', 'Date Added'],
      dtype='str')

In [16]:
Netflixshow["Director"]=Netflixshow["Director"].fillna("Unknown",inplace=True)
Netflixshow["Cast"]=Netflixshow["Cast"].fillna("Not Avaliable",inplace=True)
Netflixshow["Production Country"]=Netflixshow["Production Country"].fillna(" Location Not Mention ")
Netflixshow["Imdb Score"]=Netflixshow["Imdb Score"].fillna("6.5/10")

C:\Users\pvino\AppData\Local\Temp\ipykernel_4340\3891863483.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  Netflixshow["Director"]=Netflixshow["Director"].fillna("Unknown",inplace=True)
C:\Users\pvino\AppData\Local\Temp\ipykernel_4340\3891863483.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  Netflixshow["Cast"]=Netflixshow["Cast"].fillna("Not Avaliable",inplace=True)

In [17]:
Netflixshow.isnull().sum()

Show Id                  0
Title                    0
Description              0
Director                 0
Genres                   0
Cast                     0
Production Country       0
Release Date             3
Rating                   4
Duration                 3
Imdb Score               0
Content Type             0
Date Added            1335
dtype: int64

In [ ]:
Netflixshow["Release Date"]=pd.to_datetime(Netflixshow["Release Date"],)